function seqs=configSeqs_rl

seqOther={
%     domain specific
    struct('name','fish','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Fish/','startFrame',1,'endFrame',476,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','freeman3','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Freeman3/','startFrame',1,'endFrame',460,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','mountainbike','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/MountainBike/','startFrame',1,'endFrame',228,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','lemming','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Lemming/','startFrame',1,'endFrame',1336,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','tiger2','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Tiger2/','startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),... %% domain specific end
    struct('name','deer','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Deer/','startFrame',1,'endFrame',71,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','skating1','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Skating1/','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','shaking','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Shaking/','startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','singer1','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Singer1/','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','david','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/David/','startFrame',300,'endFrame',770,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','david2','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/David2/','startFrame',1,'endFrame',537,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','sylvester','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Sylvester/','startFrame',1,'endFrame',1345,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),... % lammdb = 0.1
    struct('name','mhyang','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Mhyang/','startFrame',1,'endFrame',1490,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','doll','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Doll/','startFrame',1,'endFrame',3872,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','dudek','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Dudek/','startFrame',1,'endFrame',1145,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','coke','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Coke/','startFrame',1,'endFrame',291,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','boy','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Boy/','startFrame',1,'endFrame',602,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','crossing','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Crossing/','startFrame',1,'endFrame',120,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','couple','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Couple/','startFrame',1,'endFrame',140,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','football1','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Football1/','startFrame',1,'endFrame',74,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','jogging-1','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Jogging/','startFrame',1,'endFrame',307,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','jogging-2','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Jogging/','startFrame',1,'endFrame',307,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','girl','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Girl/','startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','walking','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Walking/','startFrame',1,'endFrame',412,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','freeman4','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Freeman4/','startFrame',1,'endFrame',283,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','jumping','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Jumping/','startFrame',1,'endFrame',313,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','dog1','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Dog1/','startFrame',1,'endFrame',1350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','suv','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Suv/','startFrame',1,'endFrame',945,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','faceocc1','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/FaceOcc1/','startFrame',1,'endFrame',892,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','faceocc2','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/FaceOcc2/','startFrame',1,'endFrame',812,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','basketball','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Basketball/','startFrame',1,'endFrame',725,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','football','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Football/','startFrame',1,'endFrame',362,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','subway','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Subway/','startFrame',1,'endFrame',175,'nz',4,'ext','jpg','init_rect', [0 0 0 0]),...
    struct('name','tiger1','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Tiger1/','startFrame',1,'endFrame',354,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','soccer','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Soccer/','startFrame',1,'endFrame',392,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','walking2','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Walking2/','startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','carscale','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/CarScale/','startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','ironman','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Ironman/','startFrame',1,'endFrame',166,'nz',4,'ext','jpg','init_rect',[0,0,0,0]),...
    struct('name','skiing','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Skiing/','startFrame',1,'endFrame',81,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','matrix','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Matrix/','startFrame',1,'endFrame',100,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),... % lr = 0.8
    struct('name','freeman1','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Freeman1/','startFrame',1,'endFrame',326,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
};

seqBetter = { 
    struct('name','woman','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Woman/','startFrame',1,'endFrame',597,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','trellis','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Trellis/','startFrame',1,'endFrame',569,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','singer2','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Singer2/','startFrame',1,'endFrame',366,'nz',4,'ext','jpg','init_rect',[0,0,0,0]),... % lamdb =0.0001
    struct('name','car4','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Car4/','startFrame',1,'endFrame',659,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','fleetface','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/FleetFace/','startFrame',1,'endFrame',707,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','bolt','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Bolt/','startFrame',1,'endFrame',350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','liquor','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/Liquor/','startFrame',1,'endFrame',1741,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','cardark','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/CarDark/','startFrame',1,'endFrame',393,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','david3','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/David3/','startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','motorrolling','path','C:\Users\ASUS\Desktop\tracker_benchmark_v1.0\dataset/MotorRolling/','startFrame',1,'endFrame',164,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
};

seqs=[seqOther,seqBetter];